# Form implementation generated from reading ui file 'wordGroup.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


try:
    from PyQt6 import QtCore, QtGui, QtWidgets
except Exception:
    from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 340)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wordGroupTableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.wordGroupTableWidget.setAlternatingRowColors(True)
        self.wordGroupTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.wordGroupTableWidget.setColumnCount(3)
        self.wordGroupTableWidget.setHorizontalHeaderLabels(["Sync", "Group", "Model"])
        self.wordGroupTableWidget.horizontalHeader().setStretchLastSection(True)
        self.wordGroupTableWidget.verticalHeader().setVisible(False)
        self.wordGroupTableWidget.setObjectName("wordGroupTableWidget")
        self.verticalLayout.addWidget(self.wordGroupTableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select groups to sync (per-group model)"))
